### PR TITLE
Added Felix Bundle Plugin scanner

### PR DESCRIPTION
**Pull request by sebplorenz**
See https://groups.google.com/forum/#!topic/jqassistant/9cYLsaTMBxI

### CODE REVIEW

**Comment by obfischer** [comment]
Dirk, can I overtake this issue? Maybe we could integrate it for version 1.3.0?

**Comment by DirkMahler** [comment]
Sure!

**Comment by hwellmann** [comment]
The name of this plugin is rather misleading. `FelixBundleScannerPlugin` sounds like a scanner for Felix bundles, and that does not really describe what the plugin in doing, apart from the fact that the term "Felix bundle" is also confusing (OSGi bundle provided by the Felix project, or any bundle running on the Felix OSGi implementation)?

As far as I can tell, the purpose of this scanner is to detect any non-standard manifest location from the `maven-bundle-plugin` configuration, so it's not about Felix or OSGi in general, but about a particular (optional!) aspect of the Maven build process for OSGi bundle artifacts.

So `MavenBundlePluginConfigScannerPlugin` might be more adequate.

> There are only two hard things in Computer Science: cache invalidation and naming things.

**Comment by DirkMahler** [comment]
@hwellmann Correct - the name of the plugin should reflect its purpose - not the technology it is based on.

**Comment by StephanPirnbaum** [comment]
Outdated, also OSGi plugin has been removed from core and archived with jQA 2.0. If this is still relevant for you, please contact us via the [Idea Hub](https://github.com/jQAssistant/jQA-Idea-Hub)

**Pull request closed without merging**
